services:
  test-db:
    image: postgres:16
    container_name: turftrack_test_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: turftrack_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d turftrack_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - turftrack_test_network

  test-redis:
    image: redis:7
    container_name: turftrack_test_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --loglevel notice
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - turftrack_test_network

networks:
  turftrack_test_network:
    driver: bridge
