services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app/"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - ALEMBIC_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - turftrack_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - turftrack_network

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A app.celery_app worker --loglevel=debug
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      - redis
    networks:
      - turftrack_network

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A app.celery_app beat --loglevel=debug --scheduler=redbeat.RedBeatScheduler
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - REDBEAT_REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/1 # Use a different DB for redbeat
      - REDBEAT_LOCK_KEY=${REDBEAT_LOCK_KEY}
      - REDBEAT_LOCK_TIMEOUT=${REDBEAT_LOCK_TIMEOUT}
    depends_on:
      - redis
      - celery_worker
    networks:
      - turftrack_network

volumes:
  frontend_node_modules:

networks:
  turftrack_network:
    external: true
