"""remove unsupported weather columns

Revision ID: 07f589e74a97
Revises: 9c11e88a9a43
Create Date: 2025-07-02 21:30:51.207182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f589e74a97'
down_revision: Union[str, None] = '9c11e88a9a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_weather', 'mean_wet_bulb_temp_c')
    op.drop_column('daily_weather', 'mean_surface_pressure_hpa')
    op.drop_column('daily_weather', 'mean_wet_bulb_temp_f')
    op.drop_column('daily_weather', 'uv_index')
    op.drop_column('daily_weather', 'mean_surface_pressure_inhg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_weather', sa.Column('mean_surface_pressure_inhg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_weather', sa.Column('uv_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_weather', sa.Column('mean_wet_bulb_temp_f', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_weather', sa.Column('mean_surface_pressure_hpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_weather', sa.Column('mean_wet_bulb_temp_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
