"""add gdd models and values tables

Revision ID: 0d3880b8471c
Revises: 71d26acb3500
Create Date: 2025-06-17 13:00:21.779746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3880b8471c'
down_revision: Union[str, None] = '71d26acb3500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gdd_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawn_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_temp', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('C', 'F', name='tempunit'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('reset_on_threshold', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lawn_id'], ['lawns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lawn_id', 'name', name='uix_lawn_name')
    )
    op.create_table('gdd_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gdd_model_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_gdd', sa.Float(), nullable=False),
    sa.Column('cumulative_gdd', sa.Float(), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gdd_model_id'], ['gdd_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gdd_values')
    op.drop_table('gdd_models')
    # ### end Alembic commands ###
