"""Add nutrient and cost_applied columns to applications

Revision ID: 28fafe01aac4
Revises: d19d954ef7c5
Create Date: 2025-06-18 15:24:55.852897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fafe01aac4'
down_revision: Union[str, None] = 'd19d954ef7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cost_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('n_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('p_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('k_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('ca_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('mg_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('s_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('fe_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('cu_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('mn_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('b_applied', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('zn_applied', sa.Float(), nullable=True))
    op.alter_column('products', 'cost_per_lb_n',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'cost_per_lb_n',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('applications', 'zn_applied')
    op.drop_column('applications', 'b_applied')
    op.drop_column('applications', 'mn_applied')
    op.drop_column('applications', 'cu_applied')
    op.drop_column('applications', 'fe_applied')
    op.drop_column('applications', 's_applied')
    op.drop_column('applications', 'mg_applied')
    op.drop_column('applications', 'ca_applied')
    op.drop_column('applications', 'k_applied')
    op.drop_column('applications', 'p_applied')
    op.drop_column('applications', 'n_applied')
    op.drop_column('applications', 'cost_applied')
    # ### end Alembic commands ###
