"""add_indexes_to_gdd_tables

Revision ID: 2a9ef610d9e8
Revises: 9ef67f1de716
Create Date: 2025-06-20 21:44:32.863219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9ef610d9e8'
down_revision: Union[str, None] = '9ef67f1de716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gdd_model_parameters_effective_from'), 'gdd_model_parameters', ['effective_from'], unique=False)
    op.create_index(op.f('ix_gdd_resets_reset_date'), 'gdd_resets', ['reset_date'], unique=False)
    op.create_index(op.f('ix_gdd_values_date'), 'gdd_values', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gdd_values_date'), table_name='gdd_values')
    op.drop_index(op.f('ix_gdd_resets_reset_date'), table_name='gdd_resets')
    op.drop_index(op.f('ix_gdd_model_parameters_effective_from'), table_name='gdd_model_parameters')
    # ### end Alembic commands ###
