"""add gdd model parameters table

Revision ID: 4f48560bc4f9
Revises: 28fafe01aac4
Create Date: 2025-06-19 13:44:30.558090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f48560bc4f9"
down_revision: Union[str, None] = "28fafe01aac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gdd_model_parameters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gdd_model_id", sa.Integer(), nullable=False),
        sa.Column("base_temp", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("reset_on_threshold", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["gdd_model_id"],
            ["gdd_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gdd_model_id", "effective_from", name="uix_gdd_model_effective_from"
        ),
    )
    # ### end Alembic commands ###

    # Create indexes for efficient lookups
    op.create_index(
        op.f("ix_gdd_model_parameters_effective_from"),
        "gdd_model_parameters",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gdd_model_parameters_gdd_model_id"),
        "gdd_model_parameters",
        ["gdd_model_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop indexes first
    op.drop_index(
        op.f("ix_gdd_model_parameters_gdd_model_id"), table_name="gdd_model_parameters"
    )
    op.drop_index(
        op.f("ix_gdd_model_parameters_effective_from"),
        table_name="gdd_model_parameters",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gdd_model_parameters")
    # ### end Alembic commands ###
