"""create applications table

Revision ID: 65e4c4a7246b
Revises: 2a1b2c3d4e5f
Create Date: 2025-06-18 12:51:35.086563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e4c4a7246b'
down_revision: Union[str, None] = '2a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawn_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('amount_per_area', sa.Float(), nullable=False),
    sa.Column('area_unit', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('lbs', 'oz', 'kg', 'g', 'gal', 'qt', 'pt', 'fl_oz', 'L', 'mL', 'bags', 'tablets', name='applicationunit'), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('planned', 'completed', 'skipped', name='applicationstatus'), nullable=False),
    sa.Column('tied_gdd_model_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lawn_id'], ['lawns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tied_gdd_model_id'], ['gdd_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
