"""add_irrigation_entries_table

Revision ID: 690dabfeedbd
Revises: 138dec82e6a6
Create Date: 2025-08-10 10:59:44.465086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690dabfeedbd'
down_revision: Union[str, None] = '138dec82e6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irrigation_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawn_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'AUTOMATIC', 'SCHEDULED', name='irrigationsource'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lawn_id'], ['lawns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_entries_date'), 'irrigation_entries', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_entries_date'), table_name='irrigation_entries')
    op.drop_table('irrigation_entries')
    # ### end Alembic commands ###
