"""create growth_potential table

Revision ID: 97738e60a9e2
Revises: c81ff552c0c6
Create Date: 2025-07-07 14:11:48.561280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97738e60a9e2"
down_revision: Union[str, None] = "c81ff552c0c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "growth_potential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("growth_potential", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "location_id", "date", name="uq_growth_potential_location_date"
        ),
    )
    op.create_index(
        op.f("ix_growth_potential_date"), "growth_potential", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_growth_potential_id"), "growth_potential", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_growth_potential_location_id"),
        "growth_potential",
        ["location_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_growth_potential_location_id"), table_name="growth_potential"
    )
    op.drop_index(op.f("ix_growth_potential_id"), table_name="growth_potential")
    op.drop_index(op.f("ix_growth_potential_date"), table_name="growth_potential")
    op.drop_table("growth_potential")
    # ### end Alembic commands ###
