"""add_mower_maintenance_system

Revision ID: 98067d4eae4f
Revises: d62599fdf5a2
Create Date: 2025-08-22 20:56:13.850011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98067d4eae4f'
down_revision: Union[str, None] = 'd62599fdf5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mowers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mower_type', sa.Enum('ROTARY', 'REEL', 'ZERO_TURN', 'RIDING', 'PUSH', 'ELECTRIC', 'ROBOTIC', name='mowertype'), nullable=False),
    sa.Column('engine_hours', sa.Integer(), nullable=False),
    sa.Column('default_mowing_time_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mower_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('OIL_CHANGE', 'AIR_FILTER', 'SPARK_PLUG', 'FUEL_FILTER', 'BLADE_SHARPENING', 'BACKLAP', 'REEL_GRINDING', 'BEDKNIFE_ADJUSTMENT', 'BELT_REPLACEMENT', 'GEAR_OIL_CHANGE', 'TRANSMISSION_SERVICE', 'BATTERY_REPLACEMENT', 'ELECTRICAL_SYSTEM_CHECK', 'TIRE_REPLACEMENT', 'WHEEL_BEARING_SERVICE', 'SAFETY_SWITCH_CHECK', 'THROTTLE_ADJUSTMENT', 'GENERAL_SERVICE', 'WINTERIZATION', 'SPRING_STARTUP', name='maintenancetype'), nullable=False),
    sa.Column('custom_name', sa.String(length=100), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=True),
    sa.Column('last_maintenance_hours', sa.Integer(), nullable=False),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mower_id'], ['mowers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mowing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mower_id', sa.Integer(), nullable=False),
    sa.Column('lawn_id', sa.Integer(), nullable=False),
    sa.Column('mowing_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lawn_id'], ['lawns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mower_id'], ['mowers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mowing_logs_mowing_date'), 'mowing_logs', ['mowing_date'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mower_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_schedule_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.Enum('OIL_CHANGE', 'AIR_FILTER', 'SPARK_PLUG', 'FUEL_FILTER', 'BLADE_SHARPENING', 'BACKLAP', 'REEL_GRINDING', 'BEDKNIFE_ADJUSTMENT', 'BELT_REPLACEMENT', 'GEAR_OIL_CHANGE', 'TRANSMISSION_SERVICE', 'BATTERY_REPLACEMENT', 'ELECTRICAL_SYSTEM_CHECK', 'TIRE_REPLACEMENT', 'WHEEL_BEARING_SERVICE', 'SAFETY_SWITCH_CHECK', 'THROTTLE_ADJUSTMENT', 'GENERAL_SERVICE', 'WINTERIZATION', 'SPRING_STARTUP', name='maintenancetype'), nullable=False),
    sa.Column('custom_name', sa.String(length=100), nullable=True),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('hours_at_maintenance', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_schedule_id'], ['maintenance_schedules.id'], ),
    sa.ForeignKeyConstraint(['mower_id'], ['mowers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_maintenance_date'), 'maintenance_logs', ['maintenance_date'], unique=False)
    op.create_table('maintenance_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maintenance_schedule_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('part_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_schedule_id'], ['maintenance_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_log_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maintenance_log_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_log_id'], ['maintenance_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uix_lawn_week_start'), 'weekly_water_summaries', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_lawn_week_start'), 'weekly_water_summaries', ['lawn_id', 'week_start'], postgresql_nulls_not_distinct=False)
    op.drop_table('maintenance_log_parts')
    op.drop_table('maintenance_parts')
    op.drop_index(op.f('ix_maintenance_logs_maintenance_date'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_mowing_logs_mowing_date'), table_name='mowing_logs')
    op.drop_table('mowing_logs')
    op.drop_table('maintenance_schedules')
    op.drop_table('mowers')
    # ### end Alembic commands ###
