"""add new weather columns for humidity, dew point, sunshine, uv, pressure, wet bulb

Revision ID: 9c11e88a9a43
Revises: d11a149fd7b1
Create Date: 2025-07-02 21:18:59.331593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c11e88a9a43'
down_revision: Union[str, None] = 'd11a149fd7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_weather', sa.Column('relative_humidity_mean', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('relative_humidity_max', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('relative_humidity_min', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('dew_point_max_c', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('dew_point_max_f', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('dew_point_min_c', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('dew_point_min_f', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('dew_point_mean_c', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('dew_point_mean_f', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('sunshine_duration_s', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('sunshine_duration_h', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('uv_index', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('mean_surface_pressure_hpa', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('mean_surface_pressure_inhg', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('mean_wet_bulb_temp_c', sa.Float(), nullable=True))
    op.add_column('daily_weather', sa.Column('mean_wet_bulb_temp_f', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_weather', 'mean_wet_bulb_temp_f')
    op.drop_column('daily_weather', 'mean_wet_bulb_temp_c')
    op.drop_column('daily_weather', 'mean_surface_pressure_inhg')
    op.drop_column('daily_weather', 'mean_surface_pressure_hpa')
    op.drop_column('daily_weather', 'uv_index')
    op.drop_column('daily_weather', 'sunshine_duration_h')
    op.drop_column('daily_weather', 'sunshine_duration_s')
    op.drop_column('daily_weather', 'dew_point_mean_f')
    op.drop_column('daily_weather', 'dew_point_mean_c')
    op.drop_column('daily_weather', 'dew_point_min_f')
    op.drop_column('daily_weather', 'dew_point_min_c')
    op.drop_column('daily_weather', 'dew_point_max_f')
    op.drop_column('daily_weather', 'dew_point_max_c')
    op.drop_column('daily_weather', 'relative_humidity_min')
    op.drop_column('daily_weather', 'relative_humidity_max')
    op.drop_column('daily_weather', 'relative_humidity_mean')
    # ### end Alembic commands ###
