"""Add cascade delete to growth potential

Revision ID: a31bd78fc81d
Revises: ebfeea980786
Create Date: 2025-07-07 15:57:11.785012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31bd78fc81d'
down_revision: Union[str, None] = 'ebfeea980786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('growth_potential_location_id_fkey'), 'growth_potential', type_='foreignkey')
    op.create_foreign_key(None, 'growth_potential', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'growth_potential', type_='foreignkey')
    op.create_foreign_key(op.f('growth_potential_location_id_fkey'), 'growth_potential', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###
