"""add disease_pressure table

Revision ID: c0ce3551337e
Revises: 07f589e74a97
Create Date: 2025-07-04 22:53:17.829919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ce3551337e'
down_revision: Union[str, None] = '07f589e74a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_pressure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('disease', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_pressure_date'), 'disease_pressure', ['date'], unique=False)
    op.create_index(op.f('ix_disease_pressure_disease'), 'disease_pressure', ['disease'], unique=False)
    op.create_index(op.f('ix_disease_pressure_id'), 'disease_pressure', ['id'], unique=False)
    op.create_index(op.f('ix_disease_pressure_location_id'), 'disease_pressure', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disease_pressure_location_id'), table_name='disease_pressure')
    op.drop_index(op.f('ix_disease_pressure_id'), table_name='disease_pressure')
    op.drop_index(op.f('ix_disease_pressure_disease'), table_name='disease_pressure')
    op.drop_index(op.f('ix_disease_pressure_date'), table_name='disease_pressure')
    op.drop_table('disease_pressure')
    # ### end Alembic commands ###
