"""add_cascade_delete_to_applications_lawn_id

Revision ID: d11a149fd7b1
Revises: 94794423d860
Create Date: 2025-06-30 12:09:26.030078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11a149fd7b1'
down_revision: Union[str, None] = '94794423d860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_lawn_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'lawns', ['lawn_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_lawn_id_fkey'), 'applications', 'lawns', ['lawn_id'], ['id'])
    # ### end Alembic commands ###
