"""add_is_forecast_to_weekly_water_summaries

Revision ID: d62599fdf5a2
Revises: e837e92544a7
Create Date: 2025-08-10 15:59:51.446475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d62599fdf5a2"
down_revision: Union[str, None] = "e837e92544a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_forecast column with default value for existing records
    op.add_column(
        "weekly_water_summaries", sa.Column("is_forecast", sa.Boolean(), nullable=True)
    )

    # Set default value for existing records (all existing records are historical)
    op.execute(
        "UPDATE weekly_water_summaries SET is_forecast = false WHERE is_forecast IS NULL"
    )

    # Make column not nullable
    op.alter_column("weekly_water_summaries", "is_forecast", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weekly_water_summaries", "is_forecast")
    # ### end Alembic commands ###
