"""add_indexes_to_task_status_table

Revision ID: de664d9dd04d
Revises: 2a9ef610d9e8
Create Date: 2025-06-20 21:45:54.406469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de664d9dd04d'
down_revision: Union[str, None] = '2a9ef610d9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_status_started_at'), 'task_status', ['started_at'], unique=False)
    op.create_index(op.f('ix_task_status_status'), 'task_status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_status'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_started_at'), table_name='task_status')
    # ### end Alembic commands ###
