"""Add rolling average columns to growth_potential

Revision ID: ebfeea980786
Revises: 97738e60a9e2
Create Date: 2025-07-07 15:48:02.642710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfeea980786'
down_revision: Union[str, None] = '97738e60a9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('growth_potential', sa.Column('gp_3d_avg', sa.Float(), nullable=True))
    op.add_column('growth_potential', sa.Column('gp_5d_avg', sa.Float(), nullable=True))
    op.add_column('growth_potential', sa.Column('gp_7d_avg', sa.Float(), nullable=True))
    op.drop_constraint(op.f('growth_potential_location_id_fkey'), 'growth_potential', type_='foreignkey')
    op.create_foreign_key(None, 'growth_potential', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'growth_potential', type_='foreignkey')
    op.create_foreign_key(op.f('growth_potential_location_id_fkey'), 'growth_potential', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.drop_column('growth_potential', 'gp_7d_avg')
    op.drop_column('growth_potential', 'gp_5d_avg')
    op.drop_column('growth_potential', 'gp_3d_avg')
    # ### end Alembic commands ###
