"""add ResetType enum and gdd_resets table

Revision ID: ff074de5ddbc
Revises: abae3f2f8c8f
Create Date: 2025-06-17 16:18:16.428963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff074de5ddbc'
down_revision: Union[str, None] = 'abae3f2f8c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gdd_resets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gdd_model_id', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.Date(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('reset_type', sa.Enum('manual', 'threshold', 'initial', name='resettype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gdd_model_id'], ['gdd_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gdd_resets')
    # ### end Alembic commands ###
