name: Unified CI/CD

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Test and Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: turftrack_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d turftrack_test" --health-interval=5s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
        ports:
          - 6379:6379
    env:
      TEST_DATABASE_URL: postgresql+asyncpg://test_user:test_password@localhost:5432/turftrack_test
      TEST_REDIS_URL: redis://localhost:6379/1
      PYTHONUNBUFFERED: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create virtual environment
        working-directory: backend
        run: uv venv

      - name: Install dependencies
        working-directory: backend
        run: uv pip install -e .

      - name: Set up database
        working-directory: backend
        run: uv run alembic upgrade head

      - name: Run tests with coverage
        id: tests
        working-directory: backend
        run: uv run pytest --cov=app --cov-report=xml --junitxml=pytest-report.xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: backend/coverage.xml

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: backend/pytest-report.xml

      - name: Generate coverage badge
        id: coverage-badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: coverage-badge.svg

  publish:
    name: Build and Push Images
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker images
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/turftrack-backend
            ghcr.io/${{ github.repository_owner }}/turftrack-celery
            ghcr.io/${{ github.repository_owner }}/turftrack-frontend
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push celery image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.celery
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
