name: Generate Coverage Badge

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      contents: write

    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          run-id: ${{ github.event.workflow_run.id }}
          path: ./coverage

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          source: "./coverage/coverage.xml"
          output: "./coverage-badge.svg"
          thresholds: "50 75"

      - name: Commit coverage badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update coverage badge"
          file_pattern: "coverage-badge.svg"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          branch: main
